# Generated by Django 5.0.6 on 2024-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d1', '0002_article_publication_delete_kebap_delete_meat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kebap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meats', models.ManyToManyField(to='d1.meat')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
