# Generated by Django 5.0.6 on 2024-06-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
