# Generated by Django 5.0.6 on 2024-07-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rank',
        ),
    ]
