# Generated by Django 5.0.6 on 2024-06-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='selected',
        ),
    ]
