# Generated by Django 5.0.6 on 2024-07-24 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_remove_category_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=uuid.uuid4, null=True),
        ),
    ]
