# Generated by Django 5.0.6 on 2024-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0003_category_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
