# Generated by Django 5.0.6 on 2024-06-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0003_remove_cartitem_cart_id_remove_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
