# Generated by Django 5.0.6 on 2024-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
