# Generated by Django 5.0.6 on 2024-06-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_alter_category_options_category_image_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
    ]
