# Generated by Django 5.0.6 on 2024-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_remove_order_total_alter_order_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='daily_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
