# Generated by Django 5.0.6 on 2024-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0007_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
