# Generated by Django 5.0.6 on 2024-07-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0009_remove_variation_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
