# Generated by Django 5.0.6 on 2024-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0010_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_id', models.PositiveIntegerField()),
                ('orderID', models.CharField(max_length=40, null=True)),
                ('transactionID', models.CharField(max_length=40, null=True)),
                ('paypal_first_name', models.CharField(max_length=40, null=True)),
                ('paypal_last_name', models.CharField(max_length=40, null=True)),
                ('paypal_email', models.EmailField(max_length=40, null=True)),
                ('paypal_id', models.CharField(max_length=40, null=True)),
                ('paypal_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('href', models.URLField(max_length=100, null=True)),
                ('form_pickup_time', models.TimeField(max_length=40, null=True)),
                ('form_email', models.EmailField(max_length=40, null=True)),
                ('form_phone', models.CharField(max_length=40, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
