# Generated by Django 5.0.6 on 2024-07-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='form_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='form_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='form_pickup_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='href',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transactionID',
        ),
    ]
