# Generated by Django 5.0.6 on 2024-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0012_remove_order_created_date_remove_order_form_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='form_email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='form_phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='form_pickup_time',
            field=models.TimeField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transactionID',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
