# Generated by Django 5.0.6 on 2024-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0013_order_form_email_order_form_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='form_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_pickup_time',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
