# Generated by Django 5.0.6 on 2024-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0014_order_form_name_alter_order_form_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='href',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
