# Generated by Django 5.0.6 on 2024-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0017_rename_created_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
