# Generated by Django 5.0.6 on 2024-08-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0018_order_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
