# Generated by Django 5.0.6 on 2024-08-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0019_alter_order_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_menu', to='p1.product'),
        ),
    ]
