# Generated by Django 5.0.6 on 2024-08-01 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0020_order_paypal_data_product_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_menu', to='p1.product'),
        ),
    ]
