# Generated by Django 5.0.6 on 2024-08-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0022_alter_order_order_data_alter_order_paypal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paypal_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
