# Generated by Django 5.0.6 on 2024-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0023_alter_order_order_data_alter_order_paypal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
