# Generated by Django 5.0.6 on 2024-08-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0024_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
