# Generated by Django 5.0.6 on 2024-08-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0025_query_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
