# Generated by Django 5.0.6 on 2024-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0026_product_rank_variation_rank_alter_category_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
