# Generated by Django 5.0.6 on 2024-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0029_alter_query_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='form_name',
            new_name='form_companyAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='form_email',
        ),
        migrations.AddField(
            model_name='order',
            name='form_companyCity',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='form_companyName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='form_companyUst',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='form_companyZip',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
