# Generated by Django 5.0.6 on 2024-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0031_order_paymentcaptureid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
